### PR TITLE
implement #[influxdb(tag)] and #[influxdb(ignore)]

### PR DESCRIPTION
**Pull request by blasrodri**
Trying to implement [this](https://github.com/Empty2k12/influxdb-rust/pull/80#issuecomment-745294040)

### CODE REVIEW

**Comment by msrd0** [comment]
Looking at the CI failure, these seem to be your problems:

 - `#[tag]` needs to be updated: https://github.com/blasrodri/influxdb-rust/blob/influx-aware-macro-attr/influxdb/src/lib.rs#L42
 - this comparision does not need owned `String`: https://github.com/blasrodri/influxdb-rust/blob/influx-aware-macro-attr/influxdb_derive/src/writeable.rs#L34 (clippy lint)
 - this test generated an empty query: https://github.com/blasrodri/influxdb-rust/blob/influx-aware-macro-attr/influxdb/tests/derive_integration_tests.rs#L27

The first two should be easy to fix, the last error I'm not sure about why that's happening. You can use `eprintln!` from any macro code to emit debug messages at compile time - try to verify that the variables, especially `is_ignored`, contain the values you expect them to.

**Comment by blasrodri** [comment]
Thanks, @msrd0 for your comments. I think I've addressed most of the issues. Unfortunately, the CI is still failing.
Any ideas on how to fix it?

**Comment by msrd0** [comment]
The error appears [here](https://github.com/blasrodri/influxdb-rust/blob/influx-aware-macro-attr/influxdb/tests/derive_integration_tests.rs#L105) - I'd assume this is because the test is asking for `humidity` data from the database, which is now an ignored field, and therefore the database does not return any rows?

**Review by msrd0 — APPROVED** [review]
Thanks for implementing this!

**Comment by Empty2k12** [comment]
Awesome! Thanks for this. Will be releasing a new version with this soon!

**Comment by Empty2k12** [comment]
Hello! I just published a change to crates.io containing your change as version `0.4.0`. Thanks again for your contribution!

**Pull request merged**
