### PR TITLE
Fix deserialization of Series in case of no values.

### LINKED ISSUE #74: DeserializationError on "SHOW DATABASES" using non-admin credentials
-   Rust Version: 1.50.0
-   Runtime version (e.g. Tokio): InfluxDB 1.8.3
-   OS Version: MacOS 10.15

Steps to Reproduce:

1. Start a fresh InfluxDB with credentials for an admin and a non-admin user. For instance:
```bash
docker run -e INFLUXDB_HTTP_AUTH_ENABLED=true -e INFLUXDB_USER=foo -e INFLUXDB_USER_PASSWORD=bar -e INFLUXDB_ADMIN_USER=admin -e INFLUXDB_ADMIN_PASSWORD=password -p 8086:8086 influxdb:1.8
```

2. Run the query `"SHOW DATABASES"` using the Serde integration and the non-admin credentials. For instance:
```rust
use influxdb::Client;
use serde::Deserialize;

#[tokio::main]
async fn main() -> Result<(), influxdb::Error> {
    let client = Client::new("http://localhost:8086", "unused").with_auth("foo", "bar");

    #[derive(Deserialize)]
    struct Database {
        name: String,
    }

    let read_query = influxdb::Query::raw_read_query("SHOW DATABASES");
    let mut result = client.json_query(read_query).await?;
    for db in &result.deserialize_next::<Database>()?.series[0].values {
        println!("{}", db.name);
    }
    Ok(())
}
```

Result:
```text
Error: DeserializationError { error: "could not deserialize: missing field `values`" }
```

### PR DESCRIPTION
**Pull request by JEnoch**
## Description

Fix deserialization of Series in case of no values. Fix #74

### Checklist
- [x] Formatted code using `cargo fmt --all`
- [x] Linted code using clippy `cargo clippy --all-targets --all-features -- -D warnings`
- [x] Updated README.md using `cargo readme -r influxdb -t ../README.tpl > README.md`
- [x] Reviewed the diff. Did you leave any print statements or unnecessary comments?
- [x] Any unfinished work that warrants a separate issue captured in an issue with a TODO code comment

### CODE REVIEW

**Comment by Empty2k12** [comment]
Hey. Thanks for this code change.

Seems like you're running into a lot of edge-cases that have not been found yet. I am very grateful for your help in fixing those and would like to apologize for this.

Merging now!

**Comment by Empty2k12** [comment]
I am not sure when I will be able to release this. Would you be comfortable using the Git version for now until we're sure that there are no other problems you're running into that should make it into a release?

**Comment by JEnoch** [comment]
Sure, that's what I just did here: eclipse-zenoh/zenoh@00e23a7 .
I'm done with the integration of InfluxDB into zenoh for now, so I probably won't find new issues in the next weeks.
But zenoh users might... 😉  
Anyhow, we won't need for a new influxdb-rust release before our final 0.5.0 release, which won't happen before end of 2020.

**Comment by Empty2k12** [comment]
Hello! I just published a change to crates.io containing your change as version `0.4.0`. Thanks again for your contribution!

**Pull request merged**
