### PR TITLE
Re-export structures from query module

### LINKED ISSUE #33: Make query module public
Now it's impossible to access `influxdb::query::write_query::Type` to use in case like this:
```
pub fn save_data<T>(&self, data: Vec<T>)
    where
        T: TimeSeries,
        influxdb::query::write_query::Type: std::convert::From<<T>::Value>
{
```
And `influxdb::query::QueryTypes` to create custom queries (for example for writing multiple values).

The solution is to make query module `pub` or to re-export structures via `pub use`

### PR DESCRIPTION
**Pull request by KiriosK**
Re-export Type, QueryType, QueryTypes, ValidQuery

Fixes #33

### CODE REVIEW

**Comment by Empty2k12** [comment]
Thank you for this PR!

Do you think we should add tests that are using these structures so we can catch them being inaccessible in the future?

**Comment by KiriosK** [comment]
Yes, it's a great idea

**Comment by Empty2k12** [comment]
Do you want to add these tests, or should I do that?

**Comment by KiriosK** [comment]
I don't clearly undestand what should they look like.
Just trying to access structures and expect that there is no panic?

**Pull request merged**
