### PR TITLE
Replace Surf with Reqwest to allow for upgrading Tokio to 1.x.

### PR DESCRIPTION
**Pull request by BoboFraggins**
I don't know if this is of interest to you, but I got into a dependency problem with Tokio. As I am more familiar with Reqwest and it is already on Tokio 1.x, I went the route of switching out Surf with Tokio. All of the tests pass locally and it appears to fully work for my use case. If you are interested in this PR, I'd be happy to clean up any changes you require, otherwise feel free to close it.

Thanks for the great library.

### CODE REVIEW

**Comment by Empty2k12** [comment]
Hello @BoboFraggins, thanks for your PR 🚀  There's already an open PR for Reqwest at #92 by @msrd0. Did you have a chance to test if that also works for you? I intended on merging it soon once the CI errors are fixed.

**Comment by Empty2k12** [comment]
I think there's only the `<dyn>` fixes missing, which are part of your PR.

**Comment by msrd0** [comment]
This PR does not seem to continue supporting async-std, which is probably undesirable

**Comment by msrd0** [comment]
I'm closing this in favour of #92

**Pull request closed without merging**
