### PR TITLE
Fix improper quoting on tag values when the value was text

### LINKED ISSUE #60: tags without quotation marks
Hey, first of all, thank you very much for the great work.

I have a question about the InfluxDbWriteable derive. I updated the influxdb crate to 0.1.0 a few days ago. 
I'm now using the InfluxDbWriteable derive instead of creating a write query. Everything works as it should, but I've noticed that the string field that I've marked as `#tag` is saved with quotation marks. (instead of saving `abc`, my influxdb instance saves the value `"abc"`.
Is the a way to store the tag field without quotation marks?

### PR DESCRIPTION
**Pull request by sparky8251**
## Description

Fixes #60 

### Checklist
- [x] Formatted code using `cargo fmt --all`
- [x] Linted code using clippy `cargo clippy --all-targets --all-features -- -D warnings` 
- [x] Updated README.md using `cargo readme > README.md`
- [x] Reviewed the diff. Did you leave any print statements or unnecessary comments?
- [x] Any unfinished work that warrants a separate issue captured in an issue with a TODO code comment

### CODE REVIEW

**Comment by sparky8251** [comment]
Looks like there were clippy lint issues as part of master and I'm unsure if I should fix them. I also tried tests but those seem broken and unable to run as well?

It's likely this test breaks a test though so if its required for merging, just going to need help getting it working so I can fix them (or at least a pointer to the broken test since the fix should be trivial).

**Comment by Empty2k12** [comment]
Thanks for fixing the issue 👍 🚀 

There should have been a CI run showing which tests fail. I'll check what that didn't trigger.

**Comment by sparky8251** [comment]
Ok, All the clippy lints and tests pass now.

The `query::write_query::tests::test_escaping` test was especially brutal and I'd spend 90% of the review time on that test as I've got it passing, but I'm only 99.9% certain I retained the initial intent behind the test.

Squashed down all my test attempts so its just 2 discrete commits. If you want 1, let me know.

**Comment by Empty2k12** [comment]
Taking a look now! Thanks for rebasing!

> The query::write_query::tests::test_escaping test was especially brutal and I'd spend 90% of the review time on that test as while I've got it passing, I'm only 99.9% certain I retained the initial intent behind the test given all the rando backslashes and double quotes in so many places.

Honestly InfluxDb line protocol is very painful. As this PR uncovered, my initial implementation is not correct even though I based the escaping parts and tests off of the official Go package.

**Comment by Empty2k12** [comment]
From what I can tell, the new behavior looks correct. All types of escaped tested in [the go sdk](https://github.com/influxdata/line-protocol/blob/master/escaper_test.go) are covered.

Thanks for creating this PR and helping make this crate better.

**Comment by sparky8251** [comment]
No problem! Using this crate to pull sensor data from embedded devices and this was something that bit me. Ended up making it incompatible with other libraries and methods of inputting data into influxdb so I _had_ to fix it :)

**Comment by Empty2k12** [comment]
I think this change will be pushed to crates.io when #62 is merged. Until then, you reference this repo directly by Git.

If you come across further problems, feel free to open issues or pull requests addressing them. All improvements appreciated.

**Pull request merged**
