### PR TITLE
Use async await

### PR DESCRIPTION
**Pull request by NeoLegends**
The changes speak for themselves. Let's wait until reqwest gets 0.10 released until we merge this. The integration tests also need fixing.

In a follow-up PR I will optimize the usage of reqwest's HTTP client.

### CODE REVIEW

**Comment by NeoLegends** [comment]
I think running async stuff in drop is UB (tests fail with SIGILL which indicates UB). I think we need to wrap the test functions manually for teardown. For example like this: https://medium.com/@ericdreichert/test-setup-and-teardown-in-rust-without-a-framework-ba32d97aa5ab

**Comment by Empty2k12** [comment]
Thanks for this PR!

My test harness was based on the post you linked. Cleanup might be omittable but will create artefacts while locally developing. Ci will create a new influxdb each run.

**Comment by NeoLegends** [comment]
I think by now this PR is best reviewed commit-by-commit. I added a commit that indicates the minimum required rust version. Tests still need fixing.

**Comment by NeoLegends** [comment]
I think the tests are fine now. The failure probably occurs because Travis does not expose secrets to PRs to avoid leaking them to untrusted code. Let's wait until reqwest makes the next release. Then I'll update this PR and we can merge this to see if the tests are truly okay.

**Comment by Empty2k12** [comment]
Sorry, for noting just now, there's already a better test harness used in #23: https://github.com/Empty2k12/influxdb-rust/pull/23/files#diff-16b1336c25d7d5d15e6e55f3e72fef07R35-R47

Is yours compatible, so I can easily fix the other PR?

**Comment by NeoLegends** [comment]
That one is clearly more concise, but currently error prone. It is very important to catch unwinds in test harnesses, so that the teardown is still executed even when the tests panic (and thus fail).

Since all the cleanups do is create and delete tables, the one from this PR can be adapted easily. My suggestion: keep the one from this PR, because it integrates better with modern tokio (no `get_runtime`, for example, test functions can use async / await freely), but update it to reduce repetition.

**Comment by Empty2k12** [comment]
Great, I appreciate your work on this PR. Once you update `reqwest` to your desired version, I will review and merge this PR.

**Comment by NeoLegends** [comment]
If you're fine with not-releasing this library for a while we can also do the merge now and wait for the new reqwest release in-tree. Then we have time to update the other PR.

**Comment by NeoLegends** [comment]
Or you merge the other PR first, we fix the test harness, and we adapt this one.

**Comment by Strum355** [comment]
reqwest 0.10.0 was just released (4hrs ago) with async/await support. Would be great if this could be wrapped up :)

**Comment by NeoLegends** [comment]
Thanks for the heads-up! I‘ll be doing the adoption in the first few days of next year.

**Comment by Strum355** [comment]
Great, thanks! And a happy new year :)On 30 Dec 2019 23:55, Moritz Gunz <notifications@github.com> wrote:Thanks for the heads-up! I‘ll be doing the adoption in the first few days of next year.

**Comment by NeoLegends** [comment]
@Empty2k12 reqwest has been updated. Please review. :)

**Comment by Empty2k12** [comment]
> test test_wrong_authed_write_and_read ... FAILED

**Comment by NeoLegends** [comment]
@Empty2k12 Tests green! Please review.

**Pull request merged**
